# Generated by Django 5.2.9 on 2026-02-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('LUXURY', 'Luxury'), ('TREKKING', 'Trekking'), ('HELI', 'Heli')], max_length=20)),
                ('image', models.ImageField(upload_to='packages/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=100, null=True)),
                ('max_people', models.PositiveIntegerField(blank=True, null=True)),
                ('trip_difficulty', models.CharField(blank=True, max_length=100, null=True)),
                ('activity', models.CharField(blank=True, max_length=100, null=True)),
                ('max_elevation', models.IntegerField(blank=True, null=True)),
                ('accommodation', models.CharField(blank=True, max_length=100, null=True)),
                ('meal', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('major_highlights', models.TextField(blank=True, null=True)),
                ('itinerary', models.TextField(blank=True, null=True)),
                ('is_hot_sale', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.destination')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
