# Generated by Django 5.2.11 on 2026-02-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='full_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='package',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='slug',
        ),
    ]
