# Generated by Django 5.2.11 on 2026-02-23 19:25

from django.db import migrations, models


def populate_package_slugs(apps, schema_editor):
    """Assign slug values to existing Package records."""
    Package = apps.get_model('app', 'Package')
    from django.utils.text import slugify

    for pkg in Package.objects.all():
        if not pkg.slug:
            base = slugify(pkg.title)
            slug = base
            counter = 1
            while Package.objects.filter(slug=slug).exclude(pk=pkg.pk).exists():
                slug = f"{base}-{counter}"
                counter += 1
            pkg.slug = slug
            pkg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_full_description_package_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.RunPython(populate_package_slugs, migrations.RunPython.noop),
    ]

def populate_package_slugs(apps, schema_editor):
    """Assign slug values to existing Package records."""
    Package = apps.get_model('app', 'Package')
    from django.utils.text import slugify

    for pkg in Package.objects.all():
        if not pkg.slug:
            base = slugify(pkg.title)
            slug = base
            counter = 1
            while Package.objects.filter(slug=slug).exclude(pk=pkg.pk).exists():
                slug = f"{base}-{counter}"
                counter += 1
            pkg.slug = slug
            pkg.save()
