# Generated by Django 5.2.11 on 2026-02-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_package_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='destination',
            name='city',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(help_text='Country name (e.g., Nepal, Thailand)', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='app.destination'),
        ),
    ]
