# Generated by Django 5.2.11 on 2026-02-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_destination_options_remove_destination_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='is_active',
        ),
    ]
