# Generated by Django 5.2.11 on 2026-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='best_season',
            field=models.CharField(blank=True, help_text='Example: Mar-May, Sep-Nov', max_length=120),
        ),
        migrations.AddField(
            model_name='destination',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='safety_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short text for destination cards'),
        ),
        migrations.AddField(
            model_name='destination',
            name='visa_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
