# Generated by Django 5.2.11 on 2026-03-05 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_destination_best_season_destination_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Package rating from 0.0 to 5.0', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
