# Generated by Django 5.2.11 on 2026-03-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_package_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_packages',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='app.package'),
        ),
    ]
