# Generated by Django 5.2.11 on 2026-03-12 18:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_inquiry_admin_reply_inquiry_replied_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.TextField(blank=True, help_text='Optional note shown only on the hot sale page.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_sale_entries', to='app.package')),
            ],
            options={
                'verbose_name': 'Hot Sale',
                'verbose_name_plural': 'Hot Sales',
                'ordering': ['-created_at'],
            },
        ),
    ]
