# Generated by Django 5.2.11 on 2026-03-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_hotsale'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='vendor.vendorprofile'),
        ),
        migrations.AddField(
            model_name='package',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='vendor.vendorprofile'),
        ),
    ]
