# Generated by Django 5.2.11 on 2026-03-23 08:53

from django.db import migrations


def backfill_vendor_ownership(apps, schema_editor):
    CustomUser = apps.get_model('app', 'CustomUser')
    Destination = apps.get_model('app', 'Destination')
    Package = apps.get_model('app', 'Package')
    VendorProfile = apps.get_model('vendor', 'VendorProfile')

    username = 'strangeland_vendor'
    email = 'vendor@strangeland.local'

    user, _ = CustomUser.objects.get_or_create(
        username=username,
        defaults={
            'email': email,
            'role': 'VENDOR',
            'is_active': True,
        },
    )

    # Ensure role is correct even if the user existed before this migration.
    if user.role != 'VENDOR':
        user.role = 'VENDOR'
        user.save(update_fields=['role'])

    vendor_profile, _ = VendorProfile.objects.get_or_create(
        user=user,
        defaults={
            'company_name': 'Strange Land',
            'is_approved': True,
        },
    )

    if vendor_profile.company_name != 'Strange Land':
        vendor_profile.company_name = 'Strange Land'
        vendor_profile.save(update_fields=['company_name'])

    Destination.objects.filter(vendor__isnull=True).update(vendor=vendor_profile)
    Package.objects.filter(vendor__isnull=True).update(vendor=vendor_profile)


def noop_reverse(apps, schema_editor):
    # Keep reverse migration non-destructive for existing production data.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customuser_role_destination_vendor_package_vendor'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_vendor_ownership, noop_reverse),
    ]
