# Generated by Django 5.2.11 on 2026-03-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_expand_booking_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='vendor',
        ),
    ]
