# Generated by Django 5.2.11 on 2026-03-31 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_destination_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activities', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_entries', to='app.package')),
            ],
            options={
                'ordering': ['day_number'],
                'constraints': [models.UniqueConstraint(fields=('package', 'day_number'), name='unique_package_day_number')],
            },
        ),
    ]
