# Generated by Django 5.2.11 on 2026-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_packageitinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitinerary',
            name='activities',
            field=models.TextField(blank=True),
        ),
    ]
