# Generated by Django 5.2.11 on 2026-04-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_packageitinerary_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitinerary',
            name='difficulty_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='distance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='max_elevation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='meals_included',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
