# Generated by Django 5.2.11 on 2026-04-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_activitycategory_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='equipment_provided',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='safety_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.activity')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
