# Generated by Django 5.2.11 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_activity_price_max_group_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
