# Generated by Django 5.2.11 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_activityimage_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='best_season',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='package',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='package',
            name='region',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
