# Generated by Django 5.2.11 on 2026-04-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_hotsale_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityimage',
            options={'ordering': ['-is_primary', 'created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='hotsale',
            name='hotsale_exactly_one_target',
        ),
        migrations.AddField(
            model_name='activity',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Admin approval status. Only approved activities are shown on the site.', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Admin approval status. Only approved packages are shown on the site.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='hotsale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('package__isnull', False), ('activity__isnull', True)), models.Q(('package__isnull', True), ('activity__isnull', False)), _connector='OR'), name='hotsale_exactly_one_target'),
        ),
    ]
