# Generated by Django 5.2.11 on 2026-04-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_activityimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided by admin if the activity is rejected. Vendor will see this.', null=True),
        ),
    ]
