# Generated by Django 5.2.11 on 2026-04-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_activity_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided by admin if the package is rejected. Vendor will see this.', null=True),
        ),
    ]
