# Generated by Django 5.2.11 on 2026-04-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_booking_payment_fields'),
        ('app', '0023_packageunavailabledate_activityunavailabledate'),
    ]

    operations = []
