# Generated by Django 5.2.11 on 2026-04-09 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_merge_20260409_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('travel_date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash on arrival'), ('BANK_TRANSFER', 'Bank transfer')], default='CASH', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=150)),
                ('nationality', models.CharField(max_length=80)),
                ('emergency_contact', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.activity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_bookings', to='app.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
