# Generated by Django 5.2.11 on 2026-04-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_activitybooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitybooking',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('CASH', 'Cash on arrival'),
                    ('ESEWA', 'eSewa'),
                    ('BANK_TRANSFER', 'Bank transfer'),
                ],
                default='CASH',
                max_length=20,
            ),
        ),
    ]
