# Generated by Django 5.2.11 on 2026-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_activity_rating_activityreview_packagereview'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activityreview',
            name='unique_activity_review_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='packagereview',
            name='unique_package_review_per_user',
        ),
        migrations.AddConstraint(
            model_name='activityreview',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='unique_activity_review_per_user'),
        ),
        migrations.AddConstraint(
            model_name='packagereview',
            constraint=models.UniqueConstraint(fields=('package', 'user'), name='unique_package_review_per_user'),
        ),
    ]
