# Generated by Django 5.2.11 on 2026-04-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_activityreview_unique_activity_review_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_activities',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='app.activity'),
        ),
    ]
