# Generated by Django 5.2.11 on 2026-04-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_customuser_favorite_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='best_season',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='app.destination'),
        ),
        migrations.AddField(
            model_name='activity',
            name='region',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
