# Generated by Django 5.2.11 on 2026-04-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_package_activity_tour_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('STANDARD', 'Standard Package'), ('LUXURY', 'Luxury'), ('TREKKING', 'Trekking'), ('HELI', 'Heli')], max_length=20),
        ),
    ]
