# Generated by Django 5.2.11 on 2026-04-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_destinationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this activity in the Trending Activities section on the homepage.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this destination in the Top Destinations section on the homepage.'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this package in the Best Packages section on the homepage.'),
        ),
    ]
