# Generated by Django 5.2.11 on 2026-04-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_inquiry_message_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='app.activity'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='app.package'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(package__isnull=False) & models.Q(activity__isnull=True))
                    | (models.Q(package__isnull=True) & models.Q(activity__isnull=False))
                ),
                name='inquiry_exactly_one_target',
            ),
        ),
    ]
