# Generated by Django 5.2.11 on 2026-04-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_inquiry_activity_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitybooking',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash on arrival'), ('ESEWA', 'eSewa')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash on arrival'), ('ESEWA', 'eSewa')], default='CASH', max_length=20),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('money_holder', models.CharField(choices=[('PLATFORM', 'Platform'), ('VENDOR', 'Vendor')], max_length=20)),
                ('settlement_direction', models.CharField(choices=[('PLATFORM_TO_VENDOR', 'Platform pays Vendor'), ('VENDOR_TO_PLATFORM', 'Vendor pays Platform')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='app.activitybooking')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='app.booking')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('activity_booking__isnull', True)), models.Q(('booking__isnull', True), ('activity_booking__isnull', False)), _connector='OR'), name='settlement_exactly_one_booking')],
            },
        ),
    ]
